##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.17.1] date: [Wed Sep 20 17:11:12 BST 2023] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = pmc


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
main.c \
drivers/gpio.c \
drivers/adc.c \
drivers/dma.c \
drivers/i2c.c \
drivers/rng.c \
drivers/tim.c \
drivers/usart.c \
drivers/stm32l4xx_it.c \
drivers/stm32l4xx_hal_msp.c \
drivers/stm32l4xx_hal_timebase_tim.c \
drivers/system_stm32l4xx.c \
libs/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_adc.c \
libs/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_adc_ex.c \
libs/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal.c \
libs/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c.c \
libs/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c_ex.c \
libs/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc.c \
libs/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc_ex.c \
libs/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash.c \
libs/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash_ex.c \
libs/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash_ramfunc.c \
libs/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_gpio.c \
libs/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma.c \
libs/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma_ex.c \
libs/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr.c \
libs/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr_ex.c \
libs/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_cortex.c \
libs/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_exti.c \
libs/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rng.c \
libs/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim.c \
libs/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim_ex.c \
libs/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_uart.c \
libs/Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_uart_ex.c \
libs/Middlewares/Third_Party/FreeRTOS/Source/croutine.c \
libs/Middlewares/Third_Party/FreeRTOS/Source/event_groups.c \
libs/Middlewares/Third_Party/FreeRTOS/Source/list.c \
libs/Middlewares/Third_Party/FreeRTOS/Source/queue.c \
libs/Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c \
libs/Middlewares/Third_Party/FreeRTOS/Source/tasks.c \
libs/Middlewares/Third_Party/FreeRTOS/Source/timers.c \
libs/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/cmsis_os2.c \
libs/Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c \
libs/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c \
\
apps/apps.c \
apps/power/power.c \
apps/system/system.c \
apps/system/button.c \
apps/system/blink.c \
\
drivers/usbpd.c \
drivers/logging.c \
drivers/pipe_interface_freertos.c \
\
submodules/embedlib/stusb4500/stusb4500.c \
submodules/embedlib/log/log.c \
submodules/embedlib/act2861/act2861.c \
submodules/embedlib/act2861/charger.c \
\
libs/stusb4500_nvm/USBPD_CUST_NVM_API.c \
\
submodules/CameraMessages/cpubsub/cpubsub.c

# ASM sources
ASM_SOURCES =  \
startup_stm32l431xx.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32L431xx \
-DLOG_USE_COLOR


# AS includes
AS_INCLUDES =  \
-Idrivers

# C includes
C_INCLUDES =  \
-Idrivers \
\
-Ilibs/Drivers/STM32L4xx_HAL_Driver/Inc \
-Ilibs/Drivers/STM32L4xx_HAL_Driver/Inc/Legacy \
-Ilibs/Middlewares/Third_Party/FreeRTOS/Source/include \
-Ilibs/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 \
-Ilibs/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F \
-Ilibs/Drivers/CMSIS/Device/ST/STM32L4xx/Include \
-Ilibs/Drivers/CMSIS/Include \
-Ilibs/stusb4500_nvm \
\
-Isubmodules/embedlib/stusb4500 \
-Isubmodules/embedlib/log \
-Isubmodules/embedlib/act2861 \
-Isubmodules/CameraMessages/cpubsub \
-Isubmodules/CameraMessages \
\
-Iapps \
-Iapps/system \
-Iapps/power \


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections -Werror

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32L431RBTx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections -u _printf_float

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
